// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxgcbdavccgzwidythuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4Z2NiZGF2Y2NnendpZHl0aHVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDA2ODAsImV4cCI6MjA2ODM3NjY4MH0.EpJg5BYzyHEkNQtL0e-poiSbEk6i43zHeOhgWtQ-Qlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});